### ISSUE TITLE
How to correctly use the ESLint config in Node.js in conjunction with ESLint

### ISSUE THREAD

**Issue by croatialu** [antfu/eslint-config#361]
I need to run eslint in nodejs to detect the code, I use the following configuration, but I am having problems, how do I use the eslint config in nodejs

![image](https://github.com/antfu/eslint-config/assets/22277972/fd12b737-8ad3-46bc-82e5-e536e59e945c)

``` js
// eslint.config.js
import antfu from '@antfu/eslint-config'

export default antfu({
  typescript: true,
  vue: true,
  jsx: true,

  unocss: true,
  ignores: []
}, {
  rules: {
    'no-console': 'warn',
    'complexity': ['warn', 10],
  },
})


```

``` 
➜ DEBUG=eslint:* npx tsx ./scripts/ci-lint
  eslint:rules Loading rule 'no-warning-comments' (remaining=290) +0ms
  eslint:rules Loading rule 'block-spacing' (remaining=289) +239ms
  eslint:rules Loading rule 'brace-style' (remaining=288) +1ms
  eslint:rules Loading rule 'comma-dangle' (remaining=287) +2ms
  eslint:rules Loading rule 'dot-notation' (remaining=286) +10ms
  eslint:rules Loading rule 'indent' (remaining=285) +5ms
  eslint:rules Loading rule 'init-declarations' (remaining=284) +3ms
  eslint:rules Loading rule 'key-spacing' (remaining=283) +1ms
  eslint:rules Loading rule 'keyword-spacing' (remaining=282) +1ms
  eslint:rules Loading rule 'lines-around-comment' (remaining=281) +2ms
  eslint:rules Loading rule 'lines-between-class-members' (remaining=280) +1ms
  eslint:rules Loading rule 'max-params' (remaining=279) +1ms
  eslint:rules Loading rule 'no-dupe-class-members' (remaining=278) +12ms
  eslint:rules Loading rule 'no-empty-function' (remaining=277) +2ms
  eslint:rules Loading rule 'no-extra-parens' (remaining=276) +2ms
  eslint:rules Loading rule 'no-extra-semi' (remaining=275) +2ms
  eslint:rules Loading rule 'no-invalid-this' (remaining=274) +7ms
  eslint:rules Loading rule 'no-loop-func' (remaining=273) +1ms
  eslint:rules Loading rule 'no-loss-of-precision' (remaining=272) +1ms
  eslint:rules Loading rule 'no-magic-numbers' (remaining=271) +0ms
  eslint:rules Loading rule 'no-restricted-imports' (remaining=270) +13ms
  eslint:rules Loading rule 'no-unused-expressions' (remaining=269) +25ms
  eslint:rules Loading rule 'no-useless-constructor' (remaining=268) +2ms
  eslint:rules Loading rule 'object-curly-spacing' (remaining=267) +2ms
  eslint:rules Loading rule 'prefer-destructuring' (remaining=266) +4ms
  eslint:rules Loading rule 'quotes' (remaining=265) +21ms
  eslint:rules Loading rule 'semi' (remaining=264) +6ms
  eslint:rules Loading rule 'space-before-blocks' (remaining=263) +1ms
  eslint:rules Loading rule 'space-infix-ops' (remaining=262) +2ms
/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:272
            throw new Error(`ESLint configuration in ${source} is invalid:\n${this.formatErrors(validateSchema.errors)}`);
                  ^


Error: ESLint configuration in --config is invalid:
        - Unexpected top-level property "default".

    at ConfigValidator.validateConfigSchema (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:272:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/config-array-factory.js:673:19)
    at ConfigArrayFactory._loadConfigData (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/config-array-factory.js:638:21)
    at ConfigArrayFactory.loadFile (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/config-array-factory.js:504:40)
    at createCLIConfigArray (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:181:35)
    at CascadingConfigArrayFactory (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:256:29)
    at new CLIEngine (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/cli-engine.js:617:36)
    at new ESLint (/Users/croatialu/Workspace/my-project/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/eslint/eslint.js:430:27)
    at <anonymous> (/Users/croatialu/Workspace/my-project/scripts/ci-lint/index.ts:29:18)

Node.js v20.9.0

```

**Comment by antfu** [comment]
I believe this is not related to this config, you should check ESLint's docs to see how you load with flat config programmatically.
