### ISSUE TITLE
CLI Error when using "no-floating-promises"

### ISSUE THREAD

**Issue by arpowers** [antfu/eslint-config#372]
### Describe the bug

When using this rule, CLI throws the error: 
```
Error: Error while loading rule 'ts/no-floating-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

To reproduce just run `npm run lint:dev` on reproduction repo.

Eslint Config looks like this: 
```ts
// @ts-check
import antfu from "@antfu/eslint-config";

export default antfu(
  {
    typescript: {
      tsconfigPath: "./tsconfig.json",
      parserOptions: {
        project: "./tsconfig.json",
        extraFileExtensions: [".vue", ".json"],
      },
    },
    rules: {
      eqeqeq: "warn",

      "import/no-cycle": [
        "error",
        {
          maxDepth: 5,
          ignoreExternal: true,
        },
      ],
      "ts/no-floating-promises": "error",
    },
  },
  {
    ignores: [
      "**/.ref/**/*",
      "**/__*",
      "node_modules",
      "dist",
      "**/.factor/**",
      ".pnpmfile.cjs",
    ],
  }
);

```

Full Error: 
```
➜ npm run lint:dev

> eslint-testing@6.0.4 lint:dev
> npm exec -- eslint . --fix


Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Error while loading rule 'ts/no-floating-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/arpowers/Projects/eslint-testing/package.json
    at getParserServices (/Users/arpowers/Projects/eslint-testing/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:21:15)
    at create (/Users/arpowers/Projects/eslint-testing/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-floating-promises.js:76:55)
    at Object.create (/Users/arpowers/Projects/eslint-testing/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
    at createRuleListeners (/Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:895:21)
    at /Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (/Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:1003:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:1730:31)
    at Linter._verifyWithFlatConfigArray (/Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:1861:21)
    at Linter.verify (/Users/arpowers/Projects/eslint-testing/node_modules/eslint/lib/linter/linter.js:1433:65)
(base)
```

### Reproduction

https://github.com/arpowers/eslint-testing

### System Info

```Shell
MacOS
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
0c1c8db2b76bb08ecf7d92a0ed47628281b44ec2 should fix it
