### ISSUE TITLE
with Nuxt: Error: Key "plugins": Cannot redefine plugin "import"

### ISSUE THREAD

**Issue by GaborTorma** [antfu/eslint-config#482]
### Describe the bug

I got a following error when I use @anftu/eslint-config with @nuxt/eslint:

```
Error: Key "plugins": Cannot redefine plugin "import".
    at new WrapperError (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/object-schema/src/object-schema.js:123:9)
    at eval (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/object-schema/src/object-schema.js:250:27)
    at ObjectSchema.merge (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/object-schema/src/object-schema.js:237:24)
    at eval (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/config-array/api.js:935:42)
    at FlatConfigArray.getConfig (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/config-array/api.js:934:39)
    at FlatConfigArray.isFileIgnored (/home/projects/github-6rwuyx-aqu4ru/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at eval (/home/projects/github-6rwuyx-aqu4ru/node_modules/eslint/lib/eslint/eslint-helpers.js:312:49)
```

### Reproduction

https://stackblitz.com/edit/github-6rwuyx-aqu4ru

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (32) x64 Intel(R) Core(TM) i9-14900KS
    Memory: 19.34 GB / 31.22 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.13.1 - /usr/bin/node
    npm: 10.8.0 - /usr/bin/npm
    pnpm: 9.1.2 - /usr/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.60
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GaborTorma** [comment]
I tried with older version of @humanwhocodes/config-array and @humanwhocodes/object-schema, but the result is same.

**Comment by GaborTorma** [comment]
The problem when mergint `antfu/imports/rules`
![2024-05-22_08-30-50](https://github.com/antfu/eslint-config/assets/11255009/aec488cc-6a5e-4856-ba41-320db984da5d)

**Comment by GaborTorma** [comment]
It works, thanx!
