### ISSUE TITLE
ConfigError: Config "antfu/imports/rules": Key "plugins": Cannot redefine plugin "import".

### ISSUE THREAD

**Issue by DavidDeSloovere** [antfu/eslint-config#506]
### Describe the bug

(not sure if this is an issue for @nuxt/eslint or this repo)

Combining `@nuxt/eslint` with `@antfu/eslint` and throws and error when linting.

```
    "@antfu/eslint-config": "^2.21.1",
    "@nuxt/eslint": "^0.3.13",
    "eslint": "^9.5.0",
    "nuxt": "^3.12.2",
    "vue": "^3.4.29",
    "vue-router": "^4.3.3"
```

Output from lint task  (npm run lint):

```
Oops! Something went wrong! :(

ESLint: 9.5.0

ConfigError: Config "antfu/imports/rules": Key "plugins": Cannot redefine plugin "import".
    at new ConfigError (/home/projects/zzmiaxavp.github/node_modules/@eslint/config-array/dist/cjs/index.cjs:253:3)
    at rethrowConfigError (/home/projects/zzmiaxavp.github/node_modules/@eslint/config-array/dist/cjs/index.cjs:302:8)
    at eval (/home/projects/zzmiaxavp.github/node_modules/@eslint/config-array/dist/cjs/index.cjs:1097:5)
    at FlatConfigArray.getConfigWithStatus (/home/projects/zzmiaxavp.github/node_modules/@eslint/config-array/dist/cjs/index.cjs:1090:43)
    at FlatConfigArray.getConfig (/home/projects/zzmiaxavp.github/node_modules/@eslint/config-array/dist/cjs/index.cjs:1119:15)
    at eval (/home/projects/zzmiaxavp.github/node_modules/eslint/lib/eslint/eslint-helpers.js:346:56)
    at eval (/home/projects/zzmiaxavp.github/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36)
    at eval (/home/projects/zzmiaxavp.github/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32)
```

### Reproduction

https://stackblitz.com/edit/github-bupefn?file=README.md

### System Info

```Shell
On my local Windows machine with pnpm, but also on stackblitz with npm


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
You will need to set standalone to false: https://eslint.nuxt.com/packages/module#custom-config-presets

**Comment by DavidDeSloovere** [comment]
OMG. I'm so sorry for wasting you time!

**Comment by xak2000** [comment]
Another catch for further readers:
After setting `standalone` to `false` in your `nuxt.config.ts` you also need to make Nuxt rebuild the ESLint configurations in the `.nuxt` folder. E.g. running `yarn dev` once is enough.
