### ISSUE TITLE
The eslint-plugin-depreciation rule cannot be used

### ISSUE THREAD

**Issue by jeffhuien** [antfu/eslint-config#628]
### Describe the bug

What should I do to use this bag normally？

`pnpm i eslint-plugin-deprecation -D` 

```ts
import antfu from "@antfu/eslint-config";

export default antfu({
  vue: true,
  stylistic: {
    indent: 2,
    quotes: "double",
    semi: true,
  },
  rules: {
    "deprecation/deprecation": "error", // I want use this
    "no-warning-comments": ["warn", { terms: ["deprecated", "obsolete"], location: "anywhere" }],
    "no-unused-vars": [
      "warn",
      {
        vars: "all",
        args: "after-used",
        caughtErrors: "all",
        ignoreRestSiblings: false,
        reportUsedIgnorePattern: false,
      },
    ],
    "no-console": "off",
  },
});

```

pnpm lint will 
```shell


Oops! Something went wrong! :(

ESLint: 9.14.0

TypeError: Key "rules": Key "deprecation/deprecation": Could not find plugin "deprecation".
    at throwRuleNotFoundError (E:\808\node_modules\.pnpm\eslint@9.14.0_jiti@2.3.3\node_modules\eslint\lib\config\rule-validator.js:66:11)
    at RuleValidator.validate (E:\808\node_modules\.pnpm\eslint@9.14.0_jiti@2.3.3\node_modules\eslint\lib\config\rule-validator.js:147:17)
    at new Config (E:\808\node_modules\.pnpm\eslint@9.14.0_jiti@2.3.3\node_modules\eslint\lib\config\config.js:243:27)
    at [finalizeConfig] (E:\808\node_modules\.pnpm\eslint@9.14.0_jiti@2.3.3\node_modules\eslint\lib\config\flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (E:\808\node_modules\.pnpm\@eslint+config-array@0.18.0\node_modules\@eslint\config-array\dist\cjs\index.cjs:1102:55)
    at FlatConfigArray.getConfig (E:\808\node_modules\.pnpm\@eslint+config-array@0.18.0\node_modules\@eslint\config-array\dist\cjs\index.cjs:1120:15)
    at entryFilter (E:\808\node_modules\.pnpm\eslint@9.14.0_jiti@2.3.3\node_modules\eslint\lib\eslint\eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///E:/808/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.<anonymous> (file:///E:/808/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:604:6)
    at async NodeHfs.walk (file:///E:/808/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:614:3)
 ELIFECYCLE  Command failed with exit code 2.
```

### Reproduction

123123

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.48 GB / 15.36 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
You didn't install the plugin - please read ESLint or the plugin's docs
